`github.com/westurner/wiki/wiki <https://github.com/westurner/wiki/wiki>`_

- `resume <https://github.com/westurner/wiki/wiki/resume>`_
- `projects <https://github.com/westurner/wiki/wiki/projects>`_
- `contributions <https://github.com/westurner/wiki/wiki/contributions>`_
- `workflow <https://github.com/westurner/wiki/wiki/workflow>`_

  - `github <https://github.com/westurner/wiki/wiki/GitHub>`_
  - `bitbucket <https://github.com/westurner/wiki/wiki/BitBucket>`_

******

**Links**

`westurner.github.io/ <https://westurner.github.io/>`_