TODO: Import contributing.rst from https://github.com/westurner/dotfiles

TODO: Import from https://wrdfiles.readthedocs.org/en/latest/workflow.html

Project Tags
=============
* TODO: Project tag color codes & swatches 