.. contents:: 

Themes
=======
* URIs
* Linked Data (RDF, RDFa, JSONLD)
* Graphs, Nodes, Edges

Projects
=========
* https://github.com/westurner/wiki/wiki/projects

Twedges
--------
* (Directed) edges between tweets, later

Trails
-------
* Sequences of actions

Overlay
--------
* EAV visualization

RDFLib Extensions
-------------------
* RDFLib IPython notebook
* RDF exploration CLI

  * https://github.com/jonathanslenders/python-prompt-toolkit
  * schema-aware tab-completion
