===========
Projects
===========

.. contents::

Projects
==========
https://github.com/westurner/wiki/wiki/ideas

provis
-------
| Src: https://github.com/westurner/provis
| Docs: https://provis.readthedocs.org/en/latest/

- See: `Ansiblers`_

Self Directed Learning
-----------------------
| Src: https://github.com/westurner/self-directed-learning
| Docs: https://westurner.github.io/self-directed-learning/
| Docs: https://self-directed-learning.readthedocs.org/en/latest/

health-marketplace
--------------------
| Src: https://github.com/westurner/health-marketplace

healthref
---------------
| Src: https://github.com/westurner/healthref
| Web: https://westurner.github.io/healthref/
 
pycd10api
---------------
| Src: https://github.com/westurner/pycd10api

eaglefin
---------------
| Src: https://bitbucket.org/westurner/eaglefin

wbcms
---------------
| Src: https://bitbucket.org/westurner/wbcms

opengov
---------------
| Src: https://github.com/westurner/opengov
| Docs: https://westurner.github.io/opengov/

presense
---------------
| Src: https://bitbucket.org/westurner/presense

notebooks
---------------
| Src: https://github.com/westurner/notebooks
| Web: https://westurner.github.io/notebooks/

workboard
-----------
| Src: https://github.com/westurner/workboard


particlewavefluid
-----------------
| Src: https://github.com/westurner/particlewavefluid

- https://github.com/westurner/three.js/tree/localflair
  - Particle Attractor Simulator UI upgrades
- Superfluid Quantum Gravity simulator
  - Normed Tensor Gaussian Splatters
    - `Mu Animation Video`_

rosettastune
-------------
| Src: https://github.com/westurner/rosettastune



sustainablefactory
-------------------
| Src: https://github.com/westurner/sustainablefactory
| Src: https://github.com/westurner/sustainablefactory/tree/main/data/chats/


transform_md
*************
| Src: https://github.com/westurner/sustainablefactory/tree/main/src/transform_md

schematool
***********
| Src: https://github.com/westurner/sustainablefactory/tree/main/src/schematool


docindex
*********
| Src: https://github.com/westurner/sustainablefactory/tree/main/src/docindex


dsport
***************
| Src: https://github.com/westurner/dsport


docutilsrs
~~~~~~~~~~~~~~~
| Src: https://github.com/westurner/dsport/tree/main/src/docutilrs

sphinxdocrs
~~~~~~~~~~~~~~~
| Src: https://github.com/westurner/dsport/tree/main/src/sphinxdocrs

pygmentsrs
~~~~~~~~~~~~~~~
| Src: https://github.com/westurner/dsport/tree/main/src/pygmentsrs

jinja2rs
~~~~~~~~~~~~~~~
| Src: https://github.com/westurner/dsport/tree/main/src/jinja2rs

myst-md-rs
~~~~~~~~~~~~~~~
| Src: https://github.com/westurner/dsport/tree/main/src/myst-md-rs

ansiblers
**********
| Src: https://github.com/westurner/ansiblers


Mu Animation Video
--------------------
| Src: https://github.com/westurner/firmware/tree/add_weather_http_json_protobufs
| Src: https://github.com/westurner/FFmpeg/tree/mu_animation_video

- 1 bit RLE to record the screen during test execution,
  then for the device simulator,
  then maybe for web-based view of the display,
  then for whiteboarding with colors and layers
  then geometric primitives per arduinoGFX or really we want binary SVG lite
  and:
- Normed Tensor Gaussian Splatters because for an ePaper display with
  1hz (on ESP32 with meshtastic/firmware)


contributions
---------------
| See: https://github.com/westurner/wiki/wiki/contributions



Tools
=======
| See: https://github.com/westurner/wiki/wiki/tools

browenv
--------
| Src: https://github.com/westurner/browenv

brw
----
| Src: https://github.com/westurner/brw
| Web: https://westurner.github.io/brw/

bobcat
---------------
| Src: https://bitbucket.org/westurner/bobcat

certtool
---------------
| Src: https://bitbucket.org/westurner/certtool

cookiecutter-saltformula
--------------------------
| Src: https://github.com/westurner/cookiecutter-saltformula

elasticsearchjsonld
--------------------
| Src: https://github.com/westurner/elasticsearchjsonld

gitchangelogger
-----------------
| Src: https://github.com/westurner/gitchangelogger

minifylet
-----------
| Src: https://github.com/westurner/minifylet

pandasrdf
---------------
| Src: https://github.com/westurner/pandasrdf

pbm
-----------------
| Src: https://github.com/westurner/pbm
| Pypi: https://pypi.python.org/pypi/pbm

pgs
---------------
| Src: https://github.com/westurner/pgs

pkgsetcomp
---------------
| Src: https://github.com/westurner/pkgsetcomp
| Pypi: https://pypi.python.org/pypi/pkgsetcomp
| Docs: http://pkgsetcomp.readthedocs.org/en/latest/

pwd
-----
| Src: https://github.com/westurner/pwd
| Web: https://westurner.github.io/pwd/

pygments-style-jellywrd
---------------------------
| Src: https://github.com/westurner/pygments-style-jellywrd

pyjobsearch
---------------
| Src: https://bitbucket.org/westurner/pyjobsearch

pyleset
---------------
| Src: https://github.com/westurner/pyleset

pyline
---------------
| Src: https://github.com/westurner/pyline
| Pypi: https://pypi.python.org/pypi/pyline
| Docs: https://pyline.readthedocs.org/en/latest/

pyliveping
------------
| Src: https://github.com/westurner/pyliveping

pypfi
---------------
| Src: https://github.com/westurner/pypfi

pyrpo
---------------
| Src: https://github.com/westurner/pyrpo
| Pypi: https://pypi.python.org/pypi/pyrpo
| Docs: https://pyrpo.readthedocs.org/en/latest/

pyrtm-task-cli
---------------
| Src: https://bitbucket.org/westurner/pyrtm-task-cli

pytracepath
-------------
| Src: https://github.com/westurner/pytracepath

pywifiloc
---------------
| Src: https://bitbucket.org/westurner/pywifiloc

redem
---------------
| Src: https://github.com/westurner/redem

rst-tools
---------------
| Src: https://github.com/westurner/rst-tools

shellcov
----------
| Src: https://github.com/westurner/shellcov

- Rust port of bashcov

spectral
---------
| Src: https://github.com/westurner/spectral

- GUI spectrum monitor with PyQt
- Ctrl-P
- Terminal

sphinxcontrib-rdf
------------------------
| Src: https://github.com/westurner/sphinxcontrib-rdf

sphinxcontrib-srclinks
------------------------
| Src: https://github.com/westurner/sphinxcontrib-srclinks

stemkiosk
---------------
| Web: https://stemkiosk.github.io/
| Src: https://github.com/stemkiosk
| Src: https://github.com/westurner/stemkiosk


tert
-----
| Src: https://github.com/westurner/tert

venvv
------
| Src:  https://github.com/westurner/venvv

- venv_ipyconfig.py

vim2vim
---------------
| Src: https://github.com/westurner/vim2vim

- See also: `dotvim`_

web.sh
---------------
| PyPI: https://pypi.python.org/pypi/web.sh
| Src: https://github.com/westurner/web.sh

workboard
---------------
| Src: https://github.com/westurner/workboard

workhours
---------------
| Src: https://github.com/westurner/workhours

Personal
==========

USA
---------------
| Src: https://github.com/westurner/USA
| Web: https://westurner.github.io/USA

tools
---------------
| https://westurner.github.io/tools/
| Src: https://github.com/westurner/tools

dotfiles
---------------
| https://westurner.github.io/dotfiles/
| Src: https://github.com/westurner/dotfiles
| Docs: https://wrdfiles.readthedocs.org/en/latest/

dotvim
---------------
| Src: https://github.com/westurner/dotvim
| Docs: https://wrdfiles.readthedocs.org/en/latest/usage.html#vim

hello_world
---------------
| Src: https://github.com/westurner/hello_world

redditlog
---------------
| Src: https://github.com/westurner/redditlog
| Web: https://westurner.github.io/redditlog/

wiki
---------------
| https://westurner.github.io/wiki/
| Src: https://github.com/westurner/wiki/wiki
| Src: https://github.com/westurner/wiki/wiki.wiki
| Src: https://github.com/westurner/wiki/wiki.wiki.git
| Src: https://github.com/westurner/wiki/wiki/projects
| Src: https://github.com/westurner/wiki/wiki/contributions
  
resume
---------------
| Web: https://westurner.github.io/pages/resume
| Web: https://westurner.github.io/resume

westurner.github.io
----------------------
| Src: https://github.com/westurner/westurner.github.io
| Web: https://westurner.github.io/
| Web: https://westurner.org/
