======
Tools
======

.. contents::

Tool Collections
=================

https://westurner.github.io/dotfiles/tools.html (originally from provis#tools)

https://bitbucket.org/westurner/bobcat/src/tip/bobcat/__init__.py#cl-57 (RDF -> ReStructuredText)

https://westurner.github.io/redditlog/#comment/c9tfxgd (Markdown comment)

https://github.com/westurner/sphinxcontrib-rdf (ReStructuredText + RDF ?-> HTML)

https://github.com/westurner/healthref/blob/gh-pages/healthref.py (RDF -> HTML (Jinja))

https://github.com/westurner/provis/blob/master/docs/tools.rst (ReStructuredText -> HTML)

https://provis.readthedocs.org/en/latest/tools.html (HTML)

https://github.com/westurner/westurner.github.io/issues/2 (RDF tools Ontology)

https://github.com/westurner/wiki/wiki/awesome-python-testing (Markdown wiki)

https://github.com/westurner/pyleset/issues/12 (Markdown comment)

