
============
Workstations
============

Tools
*********
* USB 3.0 to IDE/SATA adapter (backups, recovery, migration)


Dotfiles
------------
| Docs: https://westurner.org/dotfiles/
| Src: https://github.com/westurner/dotfiles
| Tools: https://westurner.org/tools/#dotfiles

osquery
--------
| Homepage: https://osquery.io/
| Src: https://github.com/facebook/osquery 
| Docs: https://osquery.io/docs/tables/
| Tools: https://westurner.org/tools/#osquery


* https://github.com/westurner/dotfiles/blob/develop/scripts/osquery-all.sh

Salt
------
| Docs: http://docs.saltstack.com/en/latest/
| Src: https://github.com/saltstack/salt
| Tools: https://westurner.org/tools/#salt

.. code:: bash

   salt-call --local --out=yaml grains.items
   salt-call --local --out=yaml pkg.list_pkgs


OS
***
| Tools: https://westurner.org/tools/#operating-systems

Windows
---------
| Tools: https://westurner.org/tools/#windows-notes

OSX
----
| Tools: https://westurner.org/tools/#osx-notes

iOS
----
| Tools: https://westurner.org/tools/#ios-notes

Linux
-------
| Tools: https://westurner.org/tools/#linux-notes

Android
---------
| Tools: https://westurner.org/tools/#android-notes


Wandroid
~~~~~~~~~
| Src: https://bitbucket.org/westurner/wandroid

  * https://bitbucket.org/westurner/wandroid/src/tip/setup.py
    (scripts, console_scripts entry_points)
  * https://bitbucket.org/westurner/wandroid/src/tip/scripts/configure_path.sh

    .. code:: bash

        #!/bin/bash -x
        export ANDROID_PATH="${HOME}/.local/android"
        export ANDROID_ADTPATH="${ANDROID_PATH}/adt"
        export ANDROID_SDKPATH="${ANDROID_ADTPATH}/sdk" 
        #      ANDROID_SDKPATH="~/.local/android/adt/sdk"
        export ANDROID_TOOLSPATH="${ANDROID_SDKPATH}/tools"
        #      ANDROID_TOOLSPATH="~/.local/android/adt/sdk/tools"
        export ANDROID_PTOOLSPATH="${ANDROID_SDKPATH}/platform-tools"
        #      ANDROID_PTOOLSPATH="~/.local/android/adt/sdk/platform-tools"

        export ANDROID_WORKSPACEPATH="${PROJECT_HOME}/aclipse"
        # westurner/dotfiles:
        #      ANDROID_WORKSPACEPATH="~/-wrk/aclipse"

        export PATH="${ANDROID_PTOOLSPATH}:${ANDROID_TOOLSPATH}:${PATH}"
        # westurner/dotfiles:
        #   PATH_prepend "${ANDROID_TOOLSPATH}"
        #   PATH_prepend "${ANDROID_PTOOLSPATH}"

  * [ ] ``cat scripts/postactivate >> $_BIN/postactivate # for virtualenvwrapper``


